#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NDE3ZjViNDU4YTNkNDAwMjc5NGNjOWU3MGMyNGZhOGFjYjkzODNiZjg1ODU5YzE2ZTI5YjI2MjUyMWZlNzgyZWI2OTM5ZTAyNjI5NzllOTExMGVhMjE4MjVlMDJlZWM5MzBlYQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
